[workspace]
authors = [
    "Adele Jordan <ajae2021@mymail.pomona.edu>",
    "Keeney <nkeeney@hurricaneisland.net>"
]
channels = ["conda-forge"]
name = "scallop-stable-isotope-analysis"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.3.1,<3"
python = ">=3.13.5,<3.14"
matplotlib = ">=3.10.3,<4"
scikit-learn = ">=1.7.1,<2"
plotly = ">=6.2.0,<7"
numpy = ">=2.3.2,<3"
openpyxl = ">=3.1.5,<4"
statsmodels = ">=0.14.5,<0.15"
scipy = ">=1.16.1,<2"
seaborn = ">=0.13.2,<0.14"

[pypi-dependencies]
prince = ">=0.16.1, <0.17"

