[workspace]
authors = ["[Adele Jordan] <[ajae2021@mymail.pomona.edu]>"]
channels = ["conda-forge"]
name = "Stable-Isotope"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.3.1,<3"
python = ">=3.13.5,<3.14"
matplotlib = ">=3.10.3,<4"
scikit-learn = ">=1.7.1,<2"
